### ISSUE TITLE
Error during usage

### ISSUE THREAD

**Issue by lucaspeixotot** [jgors/vimux-ipy#1]
When I use run_cell hotkey i have this error:
-----------------------------------------------------------------------------
Error detected while processing : 
Traceback (most recent call last):
File "string", line 1, in <module>
File "string", line 138, in run_cell
vim.error: Vim(python):Traceback (most recent call last):
-----------------------------------------------------------------------------

and when i use run_visual_code hotkey i have:

-----------------------------------------------------------------------------
Error detected while processing : 
Traceback (most recent call last): 
File "string", line 1, in <module> 
File "string", line 101, in run_visual_code vim.error: 
Vim(let):E354: Invalid register name: '+' 
-----------------------------------------------------------------------------

Someone can help me?

**Comment by sizhky** [comment]
I have the same issue.
